version: "3"

services:
  db:
    image: postgres:10-alpine
    environment:
      POSTGRES_DB: celeryapp
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpass
    ports:
      - "5432:5432"
    volumes:
      - celeryapp_db:/var/lib/postgresql/data
    networks:
      - django_celery

  redis:
    image: redis:6.2
    ports:
      - "6379:6379"
    command: "redis-server --appendonly yes"
    networks:
      - django_celery

  celery_worker:
    build: .
    env_file:
      - .env
    environment:
      DJANGO_LOG_LEVEL: "DEBUG"
    networks:
      - django_celery
    volumes:
      - .:/code
    working_dir: /code
    command: "celery -A django_celery worker -l INFO --concurrency=4"

  celery_beat:
    build: .
    env_file:
      - .env
    networks:
      - django_celery
    volumes:
      - .:/code
      - celerybeat_schedule:/var/run/celery
    working_dir: /code
    command: "celery -A django_celery beat -l INFO -s /var/run/celery/celerybeat-schedule"

  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - django_celery
    volumes:
      - .:/code
    working_dir: /code
    command: bash -c "python ./manage.py migrate && python ./manage.py runserver 0.0.0.0:8000"

volumes:
  celeryapp_db:
  celerybeat_schedule:

networks:
  django_celery:
    name: django_celery_net
